---
- hosts: mysql
  tasks:
  - name: Make directory for wordpress-mysql mount
    become: true
    file:
      owner: ubuntu
      group: ubuntu
      path: /mysql
      state: directory
      mode: '0755'

  - name: Running the container mysql container
    become: true
    become_method: sudo
    docker_container:
      name: mysql
      image: mysql:8.0.0
      state: started
      env:
        MYSQL_ROOT_PASSWORD: "password321"
        MYSQL_DATABASE: "wordpress"
        MYSQL_PASSWORD: "password321"
        # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
        BOOLEAN_KEY: "yes"
      volumes:
       - /mysql:/var/www/html
      ports:
       - "3306:3306"
