---
- hosts: wordpress
  tasks:
  - name: Make directory for wordpress mount
    become: true
    file:
      owner: ubuntu
      group: ubuntu
      path: /wordpress
      state: directory
      mode: '0755'  

  - name: Running the container
    become: true
    become_method: sudo
    docker_container:
      name: wordpress-marketplace
      image: wordpress:latest
      state: started
      env:
        WORDPRESS_DB_HOST: "mysql"
        WORDPRESS_DB_USER: "root"
        WORDPRESS_DB_PASSWORD: "password321"
        WORDPRESS_DB_NAME: "wordpress"
        # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
        BOOLEAN_KEY: "yes"
      links:
       - "mysql"
      volumes:
       - /wordpress:/var/www/html
      ports:
       - "8080:80"
